import type { Metadata } from "next";
import { MarketingFooter } from "../components/MarketingFooter";
import { MarketingHeader } from "../components/MarketingHeader";

export const metadata: Metadata = { title: "About GameDay Huddle | Built for Youth Football Coaches", description: "Why GameDay Huddle is built for youth football: fast sideline decisions, local-first reliability, and statistics a volunteer staff can actually use." };

export default function AboutPage() {
  return <div className="marketing-page"><MarketingHeader /><main>
    <section className="subpage-hero section-shell"><p className="section-kicker">About GameDay Huddle</p><h1>Coaching software should understand <em>the sideline.</em></h1><p>Youth football decisions happen fast, with imperfect views, bad signals, volunteer staffs, and no patience for data entry. GameDay Huddle is built for that reality and no other.</p></section>
    <section className="about-story section-shell"><div><span>THE STARTING POINT</span><h2>What if the analytics began with the call?</h2></div><div><p>Most stat tools ask someone to reconstruct the game later. GameDay Huddle connects the play a coach called, the situation it was called into, and the result that followed. That makes every number traceable and every correction useful.</p><p>The product is deliberately local-first. A crowded game day—or simply a field with weak coverage—can make the network unreliable at the exact moment a coach needs the app most. Your playbook and game log live on your device; the network helps the staff collaborate, but it never gets the final say.</p></div></section>
    <section className="principles-section"><div className="section-shell"><p className="section-kicker">What guides the build</p><div className="principles-grid"><article><b>01</b><h3>Fast beats clever</h3><p>A coach should reach the next call in one or two taps. Complexity belongs behind the screen, not on it.</p></article><article><b>02</b><h3>Honest beats magical</h3><p>We show sample size, connection state, and what the app actually knows. Confidence without context is noise.</p></article><article><b>03</b><h3>Your football is yours</h3><p>Playbooks and game logs do not disappear when a subscription ends or a network goes down.</p></article><article><b>04</b><h3>Every correction should travel</h3><p>Fix one result and every affected dashboard, rate, and season total updates from the same event log.</p></article></div></div></section>
    <section className="about-team section-shell"><div className="about-team-card"><span className="section-kicker">Built in the huddle</span><h2>A practical tool for youth coaches and the programs they run.</h2><p>We are building GameDay Huddle in close conversation with youth football coaches &mdash; the volunteers and parents who plan practices, call games, record results, and hand a program something worth reading on Monday morning.</p><a className="button" href="/contact">Talk to us <span>→</span></a></div></section>
  </main><MarketingFooter /></div>;
}
